### ISSUE TITLE
Plan to add this to MELPA?

### ISSUE THREAD

**Issue by DivineDominion** [karthink/popup-buffers#1]
That's a nifty tool! I currently use it to get rid of compilation buffers I'm not interested in (which is almost all of them).

Do you plan to push this to MELPA at one point? Would prefer that over `git clone` package management. I just assumed the package was available because of your `use-package`  example and was confused when nothing worked as expected. No I have a `:load-path` directive and the source checked out, but a note on this might be useful!

**Comment by karthink** [comment]
There are a few issues to sort out before I'm comfortable submitting to MELPA.

- The package doesn't handle window placement, so using popup-buffers by itself will result in the user's non-popup/regular windows disappearing as popups are displayed in them and then toggled. I need a way to handle the default usage behavior without destroying the user's window configuration without rewriting something like `shackle` myself.
- There's a bug where `popup-buffers-toggle-latest` toggles that last but one popup instead. I haven't had the time to fix this.
- Popup refers to mini-frames/overlays in Emacs parlance, so the name might be confusing. I don't know what to rename this package to yet.

Thanks for the heads up about the `use-package` declaration. I should add that in.

**Comment by DivineDominion** [comment]
Hmm I see. As for the name, I was thinking about something else when I read "popup", too. Summoning a window that way I'd usually call "overlay" if it was in a floating window manager; same for "sliding in/out" etc., so this is kind of peculiar :)

**Comment by karthink** [comment]
This project is now on MELPA as [Popper](https://melpa.org/#/popper).
